# Site settings
title: Ryan Pratama
email: pratama@ryan.bi
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Ryan, and this is my website. I enjoy finding out new things, reading news and current affairs, and also science and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ryan.bi" # the base hostname & protocol for your site

github_username:  ryanbi

# Build settings
markdown: kramdown

sass:
    style: :compressed

gems:
  - jekyll-sitemap